name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish model nuget package
      uses: myci-actions/publish-nuget@5
      with:
        filename: 'Model\bin\Release\*.nupkg'
        api-key: ${{ secrets.NUGET_API_KEY }}
    - name: publish persistence nuget package
      uses: myci-actions/publish-nuget@5
      with:
        filename: 'Persistence\bin\Release\*.nupkg'
        api-key: ${{ secrets.NUGET_API_KEY }}
    - name: publish servicehost nuget package
      uses: myci-actions/publish-nuget@5
      with:
        filename: 'ServiceHost\bin\Release\*.nupkg'
        api-key: ${{ secrets.NUGET_API_KEY }}
